spring.application.name=Spring_Security_brief
spring.datasource.url=jdbc:postgresql://localhost:5432/springsecurity
spring.datasource.username=postgres
spring.datasource.password=postgres
jwt.secret=99d36a96cdcbb3a7b525c622238aafa5633e67e14cd4d5797e033873156a7201
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
